name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org

      - name: Configure Git User
        run: |
          git config --global user.email "2991205548@qq.com"
          git config --global user.name "cycleccc"

      - name: Check if able to publish changes
        run: npm whoami # will throw and exit if npm is not ready to publish

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Unit test
        run: yarn run test 

      - name: E2E test
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: yarn run example
          wait-on: 'http://localhost:8881/examples/default-mode.html'   

      - name: Publish npm
        run: yarn run release:package  --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
